### ISSUE TITLE
SF: Download draft as USFM file

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/serval#264] opened 2024-01-08 19:36 UTC
Allow the SF user to download a AI-generated book draft as a USFM file.

- For teams that are using the AI-generated drafts as a quality checking tool, this download option would allow them to create the draft and save it, but without incorporating it into the project.
- For teams that are working in a secure setting, this download option would allow them to create the draft and share it with a teammate through an alternate channel with better security.
- For teams that want to compare the initial AI-generated draft to the first draft during team checking, this download option would allow the team to save the initial draft for later comparison.

**Comment by johnml1135** [comment] 2024-01-09 12:26
Duplicate of https://github.com/sillsdev/serval/issues/242

**Comment by mmartin9684-sil** [comment] 2024-01-09 12:45
This is *not* the same as #242.  That one's talking about a Serval feature.  This one is asking for a Scripture Forge feature - a user interface enhancement that will let the SF user download a draft.

**Comment by johnml1135** [comment] 2024-02-15 21:14
This would be used for creating a draft for reviewing against an existing draft.
Note, that for Serval, if there is any text in the target for the specific segment (verse), it will not create a pretranslation.  The target verses would need to be cleared out of the incoming texts before it got into Serval.

**Comment by johnml1135** [comment] 2024-02-15 21:24
This is just for the download button.  For the drafting all content, even if it is already in the target project, see https://github.com/sillsdev/serval/issues/320.

**Comment by pmachapman** [comment] 2024-03-20 21:47
See https://jira.sil.org/browse/SF-2616

**Closed by pmachapman** 2024-03-20 21:47 UTC
Labels: enhancement, Scripture Forge, requirement, field idea
