### ISSUE TITLE
Draft Request not proceeding; unexpected last draft config in SF

### ISSUE THREAD

**Issue by bhartmoore** [sillsdev/serval#479] opened 2024-09-06 15:55 UTC
I cancelled a drafting request from test project SFd_bap sent yesterday that never moved beyond queued. It was to utilize "fast training" for testing purposes. 

After cancelling and requeuing it, the "last draft settings" config (screenshot 1) indicates NLT07 as the `alternateSource`. However, there was no alternate source selected (screenshot 2). The books for training and drafting correspond to my request, rather than to the old draft present beforehand. 

The requeued draft has not progressed to training in the last 24 hours and I can't see a record of it in ClearML.

Translation Engine Id: 66d8be5fa365d343d78ab24c per SF "Diagnostic Information"

![image (7)](https://github.com/user-attachments/assets/0cacf54f-acc9-446d-9be0-05baa87d5f40)

![image (8)](https://github.com/user-attachments/assets/7fb52b70-d514-45cf-8f89-215685665578)

**Comment by Nateowami** [comment] 2024-09-09 15:51
@bhartmoore I believe these are two completely separate issues:
- Draft not running correctly
- Configuration being shown is confusing

The config being shown actually is correct; there's a separate `alternateSourceEnabled` setting that is set to false, and it's therefore not used. But if you were to enable the checkbox, that source would re-appear. It's still part of the raw config, because we don't want to forget what was selected.

**Comment by bhartmoore** [comment] 2024-09-09 16:02
Thanks - I first sent this to John in Slack, thinking it may be relevant to an issue he mentioned. He asked me to open an issue. I mentioned that there were two separate issues involved, but I included them both since I didn't get a reply about which was of interest. 

I see now that since `alternateSourceEnabled` is false, that is not being used in this case - thanks! This issue can be about "Draft requests not proceeding" going forward, assuming it's needed on that account.

**Comment by johnml1135** [comment] 2024-11-04 14:45
I believe this issue was from here: https://github.com/sillsdev/serval/issues/480 and was caused by the locking issue.  I will close this.  If there is still more to do, we can reopen it.

**Closed by johnml1135** 2024-11-04 14:45 UTC
