### ISSUE TITLE
Paratext project documentation

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#139] opened 2023-09-22 20:01 UTC
Issue:
- I still keep getting the 404 error messages when I try to get pretranslations. Could you help me with that?
Answer
- If the corpus is a Paratext project, then the "textIds" in the "pretranslate" section should be the books that you want to generate translations for (MAT, MRK, LUK, JHN, etc).

Therefore, we should update build/pretranslate swagger doc with this information.

**Comment by Enkidu93** [comment] 2023-09-26 14:20
@johnml1135 Do you have an example set-up/project getting this to work properly? I'm not clear on the intended behavior. When I add the corpus, I select the paratext project as both the source and the target?

**Comment by johnml1135** [comment] 2023-09-26 18:24
Here is the reference for books: https://github.com/sillsdev/libpalaso/blob/master/SIL.Scripture/Canon.cs

**Comment by johnml1135** [comment] 2023-09-26 18:26
Let's say "the list of all the book codes that can be used are the AllBookIds [here](https://github.com/sillsdev/libpalaso/blob/master/SIL.Scripture/Canon.cs), such as GEN,EXO,LEV etc.

**Comment by Enkidu93** [comment] 2023-09-28 13:10
Closed in merge above.

**Closed by Enkidu93** 2023-09-28 13:10 UTC
Labels: documentation
