### ISSUE TITLE
500 codes for bad engine types

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#288] opened 2024-01-24 14:49 UTC
It should not give a 500 code for a bad engine type - likely a 422 or a 405.  I got this error:

```
serval_cntr          |       Connection id "0HN0ST6URI7V3", Request id "0HN0ST6URI7V3:00000007": An unhandled exception was thrown by the application.
serval_cntr          |       System.InvalidOperationException: Could not resolve the address for gRPC client 'Smttransfer'. Set an address when registering the client: services.AddGrpcClient<TranslationEngineApiClient>(o => o.Address = new Uri("https://localhost:5001"))
serval_cntr          |          at Grpc.Net.ClientFactory.Internal.GrpcCallInvokerFactory.CreateInvoker(EntryKey key)
serval_cntr          |          at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
serval_cntr          |          at Grpc.Net.ClientFactory.Internal.GrpcCallInvokerFactory.CreateInvoker(String name, Type type)
serval_cntr          |          at Grpc.Net.ClientFactory.Internal.DefaultGrpcClientFactory.CreateClient[TClient](String name)
serval_cntr          |          at Serval.Translation.Services.EngineService.CreateAsync(Engine engine, CancellationToken cancellationToken) in /home/johnml1135/repos/serval/src/Serval.Translation/Services/EngineService.cs:line 131
serval_cntr          |          at Serval.Translation.Services.EngineService.CreateAsync(Engine engine, CancellationToken cancellationToken) in /home/johnml1135/repos/serval/src/Serval.Translation/Services/EngineService.cs:line 150
serval_cntr          |          at Serval.Translation.Controllers.TranslationEnginesController.CreateAsync(TranslationEngineConfigDto engineConfig, IIdGenerator idGenerator, CancellationToken cancellationToken) in /home/johnml1135/repos/serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs:line 134
serval_cntr          |          at lambda_method354(Closure, Object)
```

And the response from the server was:
```
500
Undocumented
Error: Internal Server Error
```

**Comment by johnml1135** [comment] 2024-01-24 17:39
Also for bad build options:
```
serval_cntr          |       MongoDB.Bson.BsonSerializationException: An error occurred while serializing the Options property of class Serval.Translation.Models.Build: Type System.Text.Json.JsonElement is not configured as a type that is allowed to be serialized for this instance of ObjectSerializer.
serval_cntr          |        ---> MongoDB.Bson.BsonSerializationException: Type System.Text.Json.JsonElement is not configured as a type that is allowed to be serialized for this instance of ObjectSerializer.
serval_cntr          |          at MongoDB.Bson.Serialization.Serializers.ObjectSerializer.SerializeDiscriminatedValue(BsonSerializationContext context, BsonSerializationArgs args, Object value, Type actualType)
```

with a similarly cryptic 500 response.

**Comment by ddaspit** [comment] 2024-01-24 22:36
If these are endpoints that specify the engine type in the URL, then we should return a 404.

**Comment by Enkidu93** [comment] 2024-02-08 19:45
@johnml1135  I cannot recreate this issue. @ddaspit  `BadRequestExceptionFilter` covers it (unless we want to catch and rethrow or something). I tried other endpoints as well including ones with the engine as part of the url, and I couldn't manage to get any unexpected errors. (Also, the options issue is fixed with your changes, right, John?) Should we close this?

**Comment by ddaspit** [comment] 2024-02-08 21:24
This exception wasn't caused by an incorrect engine type. It looks like it might have simply been an error connecting to the Machine engine server. A 500 is appropriate in that case, so we can probably close this.

**Comment by Enkidu93** [comment] 2024-02-09 18:06
I do think it still involved an incorrect engine type `"...Could not resolve the address for gRPC client 'Smttransfer'..."` (notice the lowercase 't' - unless it's insensitive at that point), but since it's an `InvalidOperationException`, it's caught by the filter Damien added. Regardless, I believe the two issues mentioned here are covered.

**Closed by Enkidu93** 2024-02-09 18:06 UTC
Labels: bug
