### ISSUE TITLE
504 Gateway timeout on QA

### ISSUE THREAD

**Issue by pmachapman** [sillsdev/serval#450] opened 2024-08-07 21:51 UTC
When starting this build on QA, I get a 504 error:
```sh
curl -X 'POST' \
  'https://qa.serval-api.org/api/v1/translation/engines/667305f0db2383657781e0c2/builds' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
    "trainOn": [
      {
        "corpusId": "667305f3db2383657781e0c5",
        "scriptureRange": "MAT;MRK;LUK;JHN;ACT;ROM;1CO;2CO;GAL;EPH;PHP;COL;1TH;2TH;1TI;2TI;TIT;PHM;HEB;JAS;1PE;2PE;1JN;2JN;3JN;JUD;REV"
      }
    ],
    "pretranslate": [
      {
        "corpusId": "667305f3db2383657781e0c5",
        "scriptureRange": "GEN;EXO;LEV;NUM;DEU;RUT"
      }
    ],
    "options": {
      "max_steps": 20
    }
  }'
```

This was run at: 2024-08-07 21:50:17 UTC

**Comment by johnml1135** [comment] 2024-08-07 21:53
```
{"log":"info: Serval.Translation.Services.EngineService[0]\n      {\"EngineType\":\"Nmt\",\"EngineId\":\"66b287a6b754a860d1362815\",\"BuildId\":\"66b3ebe6b754a860d136507d\",\"HasOptions\":true,\"Corpora\":[{\"Id\":\"66b287aab754a860d1362818\",\"SourceLanguage\":\"es\",\"TargetLanguage\":\"en-Latn-GB\",\"TrainOnAll\":false,\"PretranslateAll\":false,\"TrainOnChapters\":{\"MAT\":{\"Chapters\":[]},\"MRK\":{\"Chapters\":[]},\"LUK\":{\"Chapters\":[]},\"JHN\":{\"Chapters\":[]},\"ACT\":{\"Chapters\":[]},\"ROM\":{\"Chapters\":[]},\"1CO\":{\"Chapters\":[]},\"2CO\":{\"Chapters\":[]},\"GAL\":{\"Chapters\":[]},\"EPH\":{\"Chapters\":[]},\"PHP\":{\"Chapters\":[]},\"COL\":{\"Chapters\":[]},\"1TH\":{\"Chapters\":[]},\"2TH\":{\"Chapters\":[]},\"1TI\":{\"Chapters\":[]},\"2TI\":{\"Chapters\":[]},\"TIT\":{\"Chapters\":[]},\"PHM\":{\"Chapters\":[]},\"HEB\":{\"Chapters\":[]},\"JAS\":{\"Chapters\":[]},\"1PE\":{\"Chapters\":[]},\"2PE\":{\"Chapters\":[]},\"1JN\":{\"Chapters\":[]},\"2JN\":{\"Chapters\":[]},\"3JN\":{\"Chapters\":[]},\"JUD\":{\"Chapters\":[]},\"REV\":{\"Chapters\":[]}},\"PretranslateChapters\":{\"RUT\":{\"Chapters\":[]}},\"TrainOnTextIds\":[],\"PretranslateTextIds\":[],\"SourceFiles\":[{\"Location\":\"/var/lib/serval/files/cki5tkxl.tle\",\"Format\":1,\"TextId\":\"667990f288132b08782858b5\"}],\"TargetFiles\":[{\"Location\":\"/var/lib/serval/files/chjqvgri.ncr\",\"Format\":1,\"TextId\":\"667990f288132b08782858b5\"}]}],\"Options\":{\"max_steps\":20},\"Event\":\"BuildRequest\",\"ModelRevision\":2,\"ClientId\":\"E4i07fEZraBMVQdCbDKR949GaMf4V8Jk@clients\"}\n","stream":"stdout","time":"2024-08-07T21:49:27.050332437Z","type":"info","source":"Serval.Translation.Services.EngineService"}
```

**Comment by pmachapman** [comment] 2024-08-07 21:53
The error page:
```html
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>


<title>qa.serval-api.org | 504: Gateway time-out</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" />


</head>
<body>
<div id="cf-wrapper">
    <div id="cf-error-details" class="p-0">
        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">
              <span class="inline-block">Gateway time-out</span>
              <span class="code-label">Error code 504</span>
            </h1>
            <div>
               Visit <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_504&utm_campaign=qa.serval-api.org" target="_blank" rel="noopener noreferrer">cloudflare.com</a> for more information.
            </div>
            <div class="mt-3">2024-08-07 21:50:17 UTC</div>
        </header>
        <div class="my-8 bg-gradient-gray">
            <div class="w-240 lg:w-full mx-auto">
                <div class="clearfix md:px-8">
                  
<div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    
    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    
  </div>
  <span class="md:block w-full truncate">You</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
    
    Browser
    
  </h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_504&utm_campaign=qa.serval-api.org" target="_blank" rel="noopener noreferrer">
    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    </a>
  </div>
  <span class="md:block w-full truncate">Sydney</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_504&utm_campaign=qa.serval-api.org" target="_blank" rel="noopener noreferrer">
    Cloudflare
    </a>
  </h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    
    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    
  </div>
  <span class="md:block w-full truncate">qa.serval-api.org</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
    
    Host
    
  </h3>
  <span class="leading-1.3 text-2xl text-red-error">Error</span>
</div>

                </div>
            </div>
        </div>

        <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
            <div class="clearfix">
                <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                    <p>The web server reported a gateway time-out error.</p>
                </div>
                <div class="w-1/2 md:w-full float-left leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
                    <p class="mb-6">Please try again in a few minutes.</p>
                </div>
            </div>
        </div>

        <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">8afa79c7eb0a5d20</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
      <span class="hidden" id="cf-footer-ip">203.211.72.107</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_504&utm_campaign=qa.serval-api.org" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div><!-- /.error-footer -->


    </div>
</div>
</body>
</html>
```

**Comment by johnml1135** [comment] 2024-08-07 21:55
@g3mackay  - do you know what could be happening here?

**Comment by johnml1135** [comment] 2024-08-30 13:04
This is a duplicate of #464.

**Closed** 2024-08-30 14:04 UTC
Labels: bug
