### ISSUE TITLE
Last verse USFM blank when source used for template 

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#442] opened 2024-07-25 20:43 UTC
This is a spin off of #408 - it for some reason is still showing up when the source USFM is chosen to be the template.  Why?

**Comment by pmachapman** [comment] 2024-07-25 20:43
This bug is only fixed on 1.5.QA5 when the template is set to Target. If the template is set to Source, the bug still occurs.

On 1.5.QA5, this endpoint https://qa.serval-api.org/api/v1/translation/engines/662e83d5d3673074e658b6db/corpora/662e83dfd3673074e658b6de/pretranslations/SUS/usfm?text-origin=OnlyPretranslated&template=Target returns:
```
...
\v 64 And Daniel became great in the sight of the people from that day and forward.
\v 65 And king Astyages was laid to rest with his fathers, and Cyrus the Persian received his kingdom.
```

While https://qa.serval-api.org/api/v1/translation/engines/662e83d5d3673074e658b6db/corpora/662e83dfd3673074e658b6de/pretranslations/SUS/usfm?text-origin=OnlyPretranslated&template=Source returns:
```
...
\v 64 And Daniel became great in the sight of the people from that day and forward.
\v 65
```

**Comment by Enkidu93** [comment] 2024-07-26 20:52
I think I've figured the issue out. I'll try and get a PR in Monday.

**Comment by Enkidu93** [comment] 2024-07-30 15:11
Alright, so the issue is versification-related like I thought: This seems to be connected to the fact that Susanna properly only has 64 verses. But in the Vulgate versification (used in the source and target above), Daniel 13:1-64 = SUS 1:1-64, but Daniel 13:65 = BEL 1:1. In other words, there shouldn't be 65 verses for Susanna. I suspect the reason that it's working with `template=Target` is because it's using relaxed `ScriptureRef`s. Why are we only using relaxed for `template=Target` and not `Source`, @ddaspit @johnml1135? - I think I was away for that PR. And how should we handle this exactly?

**Comment by ddaspit** [comment] 2024-07-30 17:10
@Enkidu93 It doesn't have to do with relaxed `ScriptureRef`s. It has to do with switching between the source and target versifications. Can you send me the source and target projects? I would like to see how the versifications are set up for each project.

**Comment by Enkidu93** [comment] 2024-07-30 17:28
> @Enkidu93 It doesn't have to do with relaxed `ScriptureRef`s. It has to do with switching between the source and target versifications. Can you send me the source and target projects? I would like to see how the versifications are set up for each project.

OK, that was actually my first guess, but the versifications are the same, so shouldn't it not matter?

Sure.
[src.zip](https://github.com/user-attachments/files/16431435/src.zip)
[trg.zip](https://github.com/user-attachments/files/16431436/trg.zip)

**Comment by ddaspit** [comment] 2024-07-30 23:27
I haven't been able to reproduce the issue yet. @Enkidu93 Have you been able to reproduce it?

**Comment by Enkidu93** [comment] 2024-07-31 13:06
> I haven't been able to reproduce the issue yet. @Enkidu93 Have you been able to reproduce it?

I have not yet. I tried at the unit-test level and couldn't. I'm gonna try and use/abuse the manual usfm test and see if I can recreate it there.

**Comment by Enkidu93** [comment] 2024-07-31 13:28
OK, I've been able to recreate the issue.

**Comment by Enkidu93** [comment] 2024-07-31 14:27
Alright, so it looks like the above is the behavior I get in testing when source refs (has content in verse 65) as opposed to target refs (no content) are used for the pretranslations. The target refs are showing as having a custom versification because of the custom.vrs. Initially, I figured the only difference between the two cases Peter was trying that could be significant was the settings files but couldn't see how that could contribute to the issue because I totally missed the custom.vrs, but it's clear that there is a mismatch now. What's the intended behavior here though, @ddaspit ?

**Comment by Enkidu93** [comment] 2024-07-31 15:57
@ddaspit Check out this branch for a reproducing test: https://github.com/sillsdev/machine/tree/test_missing_last_line

**Comment by ddaspit** [comment] 2024-08-01 01:52
I think I know what is wrong. When we extract the pretranslation segments in the `PreprocessBuildJob`, we use the `Refs` property, which maps to the source ref. When we generate the USFM, we read the refs as if it were using the target versification. This incorrect mismatch is the root of the problem. Because the source and target versifications are different, this causes a conversion to occur when we compare the verse refs. The mapping is incorrect, because the wrong versification was used for the pretranslation refs, so the comparison is incorrect. To fix the issue, we need to update the preprocessing code to return the target ref for pretranslations.

**Comment by Enkidu93** [comment] 2024-08-01 02:26
> I think I know what is wrong. When we extract the pretranslation segments in the `PreprocessBuildJob`, we use the `Refs` property, which maps to the source ref. When we generate the USFM, we read the refs as if it were using the target versification. This incorrect mismatch is the root of the problem. Because the source and target versifications are different, this causes a conversion to occur when we compare the verse refs. The mapping is incorrect, because the wrong versification was used for the pretranslation refs, so the comparison is incorrect. To fix the issue, we need to update the preprocessing code to return the target ref for pretranslations.

Cool, OK. I know the spot. I can go ahead and fix it unless you've already done so.

**Comment by ddaspit** [comment] 2024-08-01 19:06
No, I haven't fixed it.

**Comment by Enkidu93** [comment] 2024-08-06 15:10
Update: So I went ahead and made the change to using target refs on a branch and decided to test it E2E last night. Weirdly, when I retrieved the USFM after building, it worked properly on Source but not Target template (i.e., reverse behavior from before). Still digging.

**Comment by Enkidu93** [comment] 2024-08-26 13:58
@ddaspit, did you ever confirm satisfactorily for yourself that this is an issue with the versification of the project itself?

**Comment by ddaspit** [comment] 2024-08-26 16:16
I haven't had time to check it yet. I will try to this week.

**Comment by ddaspit** [comment] 2024-08-28 20:27
@Enkidu93 I finally had the opportunity to investigate the behavior. It does look like this is caused by an error in the versification. Both the source and target projects use the Vulgate versification, which defines 64 verses for SUS 1. Both the source and target projects actually contain 65 verses. Because of this error, weird things happen. If the pretranslation verse ref is converted to the project versification when it is compared, then it will work, because the verse ref is converted to the same incorrect value. This occurs if the pretranslations use the source versification and the target project is the template or vice-versa. If the verse ref isn't converted, then a match doesn't occur and the last verse is empty.

So, my investigation did find a bug in the code, but it isn't really the root cause of this issue, it just so happens to create a situation where it works. We should still fix the bug and it will fix this particular instance, but there is the deeper problem of projects with incorrect versification.

FYI, if the source and target projects had the following line in their `custom.vrs` file, then it would fix the issue:
```
SUS 1:65
```
This line updates the base versification (Vulgate) to define 65 verses in SUS 1.

**Comment by Enkidu93** [comment] 2024-09-05 00:00
Ultimately, this is because of a custom versification error. Although this investigation did uncover a bug, that bug has been fixed. In general, an error like this causes undefined behavior and that's acceptable.

**Comment by pmachapman** [comment] 2024-12-09 19:18
On 1.8.QA4, it has now flipped where when the template is set to Source the bug is fixed, while if the template is set to Target, the bug still occurs.

The endpoint https://qa.serval-api.org/api/v1/translation/engines/67562965dd170312baaa8b2b/corpora/6756296bdd170312baaa8b2e/pretranslations/SUS/usfm?text-origin=OnlyPretranslated&template=Target returns:
```
...
\v 64 And Daniel became great in the sight of the people, from that day and thenceforward.
\v 65
```

While https://qa.serval-api.org/api/v1/translation/engines/67562965dd170312baaa8b2b/corpora/6756296bdd170312baaa8b2e/pretranslations/SUS/usfm?text-origin=OnlyPretranslated&template=Source returns:
```
...
\v 64 And Daniel became great in the sight of the people, from that day and thenceforward.
\v 65 And king Astyages was gathered to his fathers: and Cyrus the Persian received his kingdom.
```

(I created this build using the older corpus, not the new parallel corpus format). @Enkidu93 I have sent you the source and target projects via email.

**Comment by Enkidu93** [comment] 2024-12-09 21:53
See pull #471 - particularly Damien's comment [here](https://github.com/sillsdev/serval/pull/471#pullrequestreview-2278362916). There's a mistake with the versification that's causing this behavior. The bug that was exposed was fixed, so I'm going to close this issue again.

**Closed by Enkidu93** 2024-12-09 21:53 UTC
Labels: bug
